application_settings:
  host: 0.0.0.0
  port: 8000
database_settings:
  require_ssl: true
email_client:
  base_url: "https://api.brevo.com"
  sender_email: "lope__@ukr.net"
  timeout_milliseconds: 10000